### ISSUE TITLE
buildpack issue - push psql to heroku

### ISSUE THREAD

**Issue by samascher** [den-materials/project-03#10]
Sams-MacBook-Air:yok-test smascher$ git add -A
Sams-MacBook-Air:yok-test smascher$ git commit -m "added changes"
On branch DB_etc
nothing to commit, working tree clean
Sams-MacBook-Air:yok-test smascher$ git push heroku master
Counting objects: 24668, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (16585/16585), done.
Writing objects: 100% (24668/24668), 33.79 MiB | 11.01 MiB/s, done.
Total 24668 (delta 6848), reused 24668 (delta 6848)
remote: Compressing source files... done.
remote: Building source:
remote: 
remote: -----> App not compatible with buildpack: https://codon-buildpacks.s3.amazonaws.com/buildpacks/heroku/nodejs.tgz
remote:        More info: https://devcenter.heroku.com/articles/buildpacks#detection-failure
remote: 
remote:  !     Push failed
remote: Verifying deploy...
remote: 
remote: !	Push rejected to yokel-app.
remote: 
To https://git.heroku.com/yokel-app.git
 ! [remote rejected]   master -> master (pre-receive hook declined)
error: failed to push some refs to 'https://git.heroku.com/yokel-app.git'

**Comment by ZebGirouard** [comment]
Found this...we had a nested folder in the git repo.  Closing.
