### ISSUE TITLE
about the server.ts file

### ISSUE THREAD

**Issue by hungmuha** [den-materials/project-03#12]
In my server.ts, I used this function in my server to start the engine ( I pulled this from the tunr exercise that we did in class) and options.req.url should return back to me the url that user put on the browser but it seems to not getting the same thing that I expected to get. It is not undefined (good news I guess) but It doesn't give me the information that I want. I have talked to Stefon about this and he doesn't really know what's going on or at least able to point me to the direction that I can look into. I don't even know what I need to look into, I have looked into the syntax of express.engine and i dont think I incorrectly set up the server file but maybe I was wrong. Thank you for helping

Link of my project
https://github.com/hungmuha/yokel/blob/master/src/server.ts

app.engine('html', (_, options, callback) => {
  const opts = { document: template, url: options.req.url };

  renderModuleFactory(AppServerModuleNgFactory, opts)
    .then(html => callback(null, html));
});

**Comment by ZebGirouard** [comment]
This is all set.  Great work, Hung!
