### ISSUE TITLE
can not push to heroku

### ISSUE THREAD

**Issue by samascher** [den-materials/project-03#13]
says it's deployed -- application error. there's an error H10 (heroku app crashed), but also... when i run the heroku run bash >> npm start it gives me the following error

ERROR in /app/src/db/dbSetup.ts (4,3): Cannot find name 'process'.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! yokel@0.0.0 prestart: `ng build --prod && ngc`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the yokel@0.0.0 prestart script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /app/.npm/_logs/2017-08-30T19_07_52_410Z-debug.log

process is part of my dbSetup.ts file: 

import { db } from '../models';

db.sequelize.sync({force: true}).then(function(){
  process.exit();
});

please help i've been stuck for hours

**Comment by ZebGirouard** [comment]
This is saying it doesn't know what `process` is, which is a Node variable.  This seems like it would be a problem locally as well.  What happens when you run `npm start` locally?
