### ISSUE TITLE
Angular universal accessing window

### ISSUE THREAD

**Issue by Astroknut** [den-materials/project-03#18]
I am trying to access the window with a WindowService, to use in my authentication service. I am getting the error 'Window is not defined' because we are using ssr with universal. Is there any way to work around this? 

Here are a few sources I have tried and haven't had any luck:

https://github.com/angular/angular/issues/15150#issuecomment-286887083

https://github.com/ui-router/angular/issues/134

Also, here is the code for my Window Service

import { Injectable } from '@angular/core';

function getWindow(): any {
	return window;
}

@Injectable()
export class WindowService {

	get nativeWindow(): any {
		return getWindow();
	}

  	constructor() { }

}

**Comment by ZebGirouard** [comment]
Chase will kill it with fire.
