### ISSUE TITLE
Heroku complains that "Can't resolve all parameters"

### ISSUE THREAD

**Issue by cg923** [den-materials/project-03#19]
Hi guys.  So, my code pushes just fine to Heroku, and I'm pretty sure I've got the database set up correctly.

But when I check heroku logs I see this error:
"Can't resolve all parameters for JournalService"

I've narrowed down that I think it has something to do with importing Http in my service.  These two articles seem to indicate as such:
https://stackoverflow.com/questions/37997824/angular-2-di-error-exception-cant-resolve-all-parameters
https://stackoverflow.com/questions/42425139/angular2-error-cant-resolve-all-parameters-for-iconservice

I've tried moving my HttpModule import around, and the declaration itself around, and it's just not working for me.  I talked to Sam and Connie about this but they're on totally different heroku problems.

Any thoughts?

**Comment by ZebGirouard** [comment]
I think we've got a good workaround at least for presentations.
