### ISSUE TITLE
How do I wait to render a view until an observable gets my data.

### ISSUE THREAD

**Issue by jeffDevelops** [den-materials/project-03#20]
I was able to send the data acquired from the first step in our user-flow (component 1) to a service for use in a sibling component. I am successfully subscribing to that data in the second step (component 2), but my view is rendering before the data comes back.

-Am I following the right approach, or should I just import component 1 and get its results that way?
-If I am following the right approach, I found these two articles that seem vaguely like my issue, but I'm not sure in which direction to go.

**Something about a Resolver...?**
https://stackoverflow.com/questions/39358828/how-to-make-angular2-wait-for-a-promise-before-rendering-component

**Safe Navigation (Elvis) Operator**
https://stackoverflow.com/questions/37565176/angular-2-view-renders-before-data-loads-in-ngoninit

**Comment by stefems** [comment]
Does the data still render in the component, even if it is late?

**Comment by jeffDevelops** [comment]
Thanks, Stefan! :)
