### ISSUE TITLE
Authentication problems

### ISSUE THREAD

**Issue by Astroknut** [den-materials/project-03#5]
Trying to incorporate Auth0

returning an error:
Failed to execute 'atob' on 'Window': The string to be decoded is not correctly encoded

in reference to code: 
var config = JSON.parse(decodeURIComponent(escape(window.atob('@@config@@'))));

**Comment by ZebGirouard** [comment]
@Astroknut , what does `@@config@@` evaluate to?  My understanding is that `atob` is expecting some sort of encoded data (what is created by running `btoa` on a string).  It seems to be complaining that `@@config@@` is not a properly encoded string, which makes sense to me.  It seems like that should be a variable.

I'd love to take a look at this tomorrow if it's still bothering you.

**Comment by Astroknut** [comment]
I'm over that hurdle. I'm going to try plugging everything in and making sure all the routing is correct this evening, so If I hit any more snags I can submit another issue before tomorrow morning! But for now this issue is resolved!

**Comment by ZebGirouard** [comment]
W00t!  Awesome news, Chase.  Closing.
