### ISSUE TITLE
NPM module install errors

### ISSUE THREAD

**Issue by m2creger** [den-materials/project-03#6]
I am trying to install sequelize and getting this error:

Unexpected token < in JSON at position 47428.

David and Everett have no idea.

Couple links I went through:

https://github.com/AtomLinter/linter-eslint/issues/824

https://github.com/atom-community/sync-settings/issues/362

https://stackoverflow.com/questions/37280274/syntaxerror-unexpected-token-in-json-at-position-0-in-react-app/37280472

**Comment by ZebGirouard** [comment]
Hi @m2creger ,

That error is complaining about a `<` symbol in what *should* be JSON.  However, it seems to be HTML (`<html>` for instance would cause that error).  I'd like to take a look at this tomorrow if you're still struggling with it.

**Comment by m2creger** [comment]
Hey Zeb,

I ended up getting it squared away. I ended up copying Alex's package-lock.json which was working and putting it in my project. There was a < symbol somewhere in it.

**Comment by ZebGirouard** [comment]
Interesting...glad you got it figured out.  Closing.
