### ISSUE TITLE
Strange error from server.ts

### ISSUE THREAD

**Issue by hungmuha** [den-materials/project-03#9]
I have an error on the server file that stated that stated "Cannot find module '@angular/platform-server' " in the terminal. 

I have checked the package.json and it is in there, I imported it correctly in the server.ts so I have no idea what to do from here.
Thank you,

**Comment by ZebGirouard** [comment]
@hungmuha , can you put the full error in there with files, line numbers, etc., and then come over to the 3rd floor lounge?  I'm at the big table.

**Comment by ZebGirouard** [comment]
Hung has moved onto a new issue now
